services:
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: museum
      MYSQL_SSL_CA: ""
      MYSQL_SSL_CERT: ""
      MYSQL_SSL_KEY: ""
      TZ: "Asia/Seoul"
    ports:
      - "1234:3306"
    networks:
      - db-network
    profiles:
      - database


  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring-network
    profiles:
      - monitoring

networks:
  db-network:
  monitoring-network:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data: