spring:
  application:
    name: science-museum-backend
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    url: ${DB_USER_URL}

  # JPA configF
  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

ai:
  url: ${AI_URL}
  port: ${AI_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, prometheus, info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG